# This is a basic workflow to help you get started with Actions

name: Automatic Merge with upstream branches
on:
  schedule:
     # actually, ~5 minutes is the highest
     # effective frequency you will get
    - cron:  '0 * 1 * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          # git config --global user.name "Weiguang.Cui Automerge"
          # git config --global user.email cuiweiguang@gmail.com
          # "git checkout master" is unnecessary, already here by default
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)
          git remote add upstream https://gitlab.cosma.dur.ac.uk/swift/swiftsim.git
          git fetch upstream
          # Neither forget the -b opt,
          # the feature/x ref is ambiguous at this stage
          # git checkout -b master origin/master
          # git merge --no-edit upstream/master
          # git push origin master
          git checkout origin/master
          git merge --no-edit upstream/master
          git push origin master
          # etc
